include:
  - project: 'camelot/support/templates/gitlab-releases-ci-template'
    ref: 'v2.2.0'
    file: '/templates/changelog.and.releases.yml'  # not ideal with Python
    #file: '/templates/changelog.and.releases.pep440.yml'    # better with Python
  - project: 'camelot/support/templates/python-ci-template'
    ref: 'v5.9.84'
    file: '/templates/python.single.yml'
  - project: 'camelot/support/templates/python-ci-template'
    ref: 'v5.9.84'
    file: '/templates/python.publish.yml'


variables:
  # path to source code projects
  PYTHON_PROJECT_PATH: "."
  PYTHON_MODULE_NAME: "capycli"
  PYTHON_TEST_CODE_PATH: "tests"
  # Disable Code Quality Check
  ENABLE_CODE_QUALITY_CHECK: "false"
  SONAR_JOBS_ACTIVE: "false"
  ENABLE_PYTHON_PRECOMMIT: "false"
  BASE_IMAGE_REF: "bookworm"
  SEMREL_CHANGELOG_FILE: "CHANGELOG_camelot.md"
  PULL_BRANCH_NAME: "pull-from-upstream"
  PULL_REQUEST_BRANCH: "create-pull-request"
  GITHUB_USERNAME: "Catalin-Roman" # TODO Replace : Used for pushing the Pull Request branch to the GitHub intermediate repo
  GITHUB_INTERMEDIATE_USERNAME: "Catalin-Roman" # TODO Replace with the GitHub username associated with the Functional Account
  GITHUB_INTERMEDIATE_REPO: "capycli-intermediate" # TODO Replace with the GitHub repository associated with the Functional Account
  GITHUB_INTERMEDIATE_URL: "https://github.com/${GITHUB_INTERMEDIATE_USERNAME}/${GITHUB_INTERMEDIATE_REPO}.git"
  GITHUB_CAPYCLI_USERNAME: "Catalin-Roman" # TODO Use "sw360"
  GITHUB_CAPYCLI_REPO: "capycli"
  GITHUB_CAPYCLI_URL: "https://github.com/${GITHUB_CAPYCLI_USERNAME}/${GITHUB_CAPYCLI_REPO}.git"

stages:
  - version
  - pull-from-upstream
  - create-pull-request
  - build
  - package
  - test
  - swag
  - publish
  - release

pull:
  stage: pull-from-upstream
  image: cr.siemens.com/camelot/support/container/gitlab-runner/curl:v0.12.20
  before_script:
  - export http_proxy=${CODE_PROXY}
  - export https_proxy=${CODE_PROXY}
  - export no_proxy=127.0.0.1,localhost,.siemens.de,.siemens.net,.siemens.com,.siemens.io,s3.dualstack.eu-central-1.amazonaws.com
  script:
    # Configure git and check curl
    - echo "Syncing with upstream repository..."
    - git config --global user.email "${GIT_AUTOMATION_EMAIL}"
    - git config --global user.name "${GIT_AUTOMATION_NAME}"
    - git config --list | grep user
    - curl --version
    # Configure the remotes
    - git remote set-url origin https://${GIT_AUTOMATION_EMAIL}:${GIT_AUTOMATION_TOKEN}@code.siemens.com/camelot/tools/capycli.git
    - git remote add upstream https://github.com/sw360/capycli.git
    - git remote -v
    # Update the local "upstream_main" branch with the changes from upstream/main and push the changes
    - git fetch upstream main -v
    - git status
    - git checkout upstream_main
    - git merge upstream/main -v # we expect no conflicts
    - git log --oneline --decorate --graph --max-count 10
    - git push -o ci.skip -v
    # Create the intermediate branch from fork_main and merge upstream_main into it
    - git checkout -b ${PULL_BRANCH_NAME} origin/fork_main
    - git push origin ${PULL_BRANCH_NAME} --force -o ci.skip
    - git merge upstream_main || echo "ERROR Merge failed, continuing anyway"
    - |
      curl --request POST "https://code.siemens.com/api/v4/projects/399725/merge_requests" \
        --header "PRIVATE-TOKEN: ${GIT_AUTOMATION_TOKEN}" \
        --header "Content-Type: application/json" \
        --data "{
          \"source_branch\": \"${PULL_BRANCH_NAME}\",
          \"target_branch\": \"fork_main\",
          \"title\": \"chore: pull from upstream repository\",
          \"description\": \"This Merge Request pulls the changes from the upstream repository and applies them to the fork.\",
          \"remove_source_branch\": true,
          \"squash\": true,
          \"assignee_ids\": [50618]
        }"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: always
  tags:
    - "$CI_RUNNER_TAG_SHARED"


create-github-pull-request:
  stage: create-pull-request
  image: cr.siemens.com/camelot/support/container/gitlab-runner/curl:v0.12.20
  before_script:
  - export http_proxy=${CODE_PROXY}
  - export https_proxy=${CODE_PROXY}
  - export no_proxy=127.0.0.1,localhost,.siemens.de,.siemens.net,.siemens.com,.siemens.io,s3.dualstack.eu-central-1.amazonaws.com
  script:
    - echo "Creating Pull Request FROM branch $PULL_REQUEST_BRANCH on GitLab project URL ${CI_PROJECT_URL} TO upstream GitHub repo ${GITHUB_CAPYCLI_URL} using INTERMEDIATE GitHub repo ${GITHUB_INTERMEDIATE_URL} "
    - git config --global user.email "${GIT_AUTOMATION_EMAIL}"
    - git config --global user.name "${GIT_AUTOMATION_NAME}"
    - git config --list | grep user
    - git remote -v
    - git remote add github-intermediate ${GITHUB_INTERMEDIATE_URL}
    - git remote -v
    - git checkout ${PULL_REQUEST_BRANCH}
    # Push the branch to the intermediate GitHub repo
    - git push https://${GITHUB_USERNAME}:${GITHUB_CONTENT_TOKEN}@github.com/${GITHUB_INTERMEDIATE_USERNAME}/${GITHUB_INTERMEDIATE_REPO}.git ${PULL_REQUEST_BRANCH} -v
    # Create the Pull Request
    - |
      curl --request POST "https://api.github.com/repos/${GITHUB_CAPYCLI_USERNAME}/${GITHUB_CAPYCLI_REPO}/pulls" \
      --header "Authorization: token ${GITHUB_PULL_REQUEST_TOKEN}" \
      --header "Content-Type: application/json" \
      --data "{
        \"title\": \"Auto PR from GitLab\",
        \"head\": \"${GITHUB_INTERMEDIATE_USERNAME}:${PULL_REQUEST_BRANCH}\",
        \"base\": \"main\",
        \"body\": \"This PR was created automatically from GitLab CI/CD.\",
        \"draft\": true
      }"
  when: manual
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web" && $CI_COMMIT_REF_NAME == $PULL_REQUEST_BRANCH'
      when: manual
    - when: never
  tags:
    - "$CI_RUNNER_TAG_SHARED"
